import os
from pathlib import Path
import re


def normalize(text: str) -> str:
    """
    Normalize client names by lowercasing, replacing spaces with underscores,
    and stripping unsafe characters.
    """
    text = text.lower().strip()
    text = text.replace(" ", "_")
    text = re.sub(r"[^a-z0-9_\-]+", "_", text)
    text = re.sub(r"_+", "_", text)
    return text.strip("_")


def create_subfolders(base_dir: Path) -> list[Path]:
    """
    Create a standard set of subfolders inside the client directory.
    """
    subfolders = [
        "01_documents",
        "02_assets",
        "03_notes",
        "04_deliverables",
    ]

    created = []
    for name in subfolders:
        folder_path = base_dir / name
        folder_path.mkdir(exist_ok=True)
        created.append(folder_path)

    return created


def write_intake_readme(base_dir: Path, client_name: str) -> Path:
    """
    Write a starter README/checklist into the client folder.
    """
    readme_path = base_dir / "README.md"
    content = f"""# Client Intake: {client_name}

This folder was automatically generated by the Client Intake Organizer.

## Initial Checklist
- [ ] Confirm client contact information
- [ ] Gather required documents
- [ ] Create project notes
- [ ] Set up communication channel
- [ ] Schedule kickoff meeting

## Folder Overview
- **01_documents** — contracts, forms, PDFs  
- **02_assets** — images, logos, brand files  
- **03_notes** — meeting notes, planning  
- **04_deliverables** — final outputs  
"""

    readme_path.write_text(content, encoding="utf-8")
    return readme_path


def main() -> None:
    print("Client Intake Organizer")
    print("-----------------------")

    root_input = input("Enter the root folder where client folders should be created: ").strip()
    root_dir = Path(root_input).expanduser().resolve()

    if not root_dir.exists() or not root_dir.is_dir():
        print("The provided root path is not a valid directory.")
        return

    client_name = input("Enter the client name: ").strip()
    if not client_name:
        print("Client name cannot be empty.")
        return

    normalized = normalize(client_name)
    client_dir = root_dir / normalized

    if client_dir.exists():
        print(f"A folder for '{client_name}' already exists at: {client_dir}")
        return

    client_dir.mkdir()
    subfolders = create_subfolders(client_dir)
    readme_path = write_intake_readme(client_dir, client_name)

    print()
    print("Client folder created successfully:")
    print(f"- {client_dir}")
    for sf in subfolders:
        print(f"  • {sf.name}")
    print(f"- README.md created at {readme_path}")


if __name__ == "__main__":
    main()
